import Head from "next/head";
import Main from "~/components/Main";
import Layout from "~/components/layout";

export default function Home() {
  return (
    <>
        <Layout>
          <Head>
            <title>Koazie - Links</title>
            <meta name="description" content="Generated by codrkoaz" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Main />
        </Layout>
    </>
  );
}
