import Head from "next/head";
import Image from "next/image";
export default function Home() {
  return (
    <>
      <Head>
        <title>KOAZIE - Links</title>
        <meta name="description" content="Generated by codrkoaz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center m-0 p-0 font-sans">
        <header>
          <Image src='/assets/koaz.jpeg' alt='joza' height={200} width={200} />

          <h1 className="text-orange-300 text-4xl">@codrkoaz</h1>
          <ul className="flex items-center flex-col">
           <li><a href="">link 1</a></li>
           <li><a href="">link 2</a></li>
           <li><a href="">link 3</a></li>
           <li><a href="">link 4</a></li>
          </ul>
        </header>

      </main>
    </>
  );
}
